version: '3.6'
services:
  iris:
    image: ghcr.io/lscalese/objectscript-syntax-for-gitlab:latest
    #build: 
    #  context: .
    #  dockerfile: Dockerfile
    #restart: always
    command: ["--check-caps", "false", "-a", "sh /home/irisowner/startRackup.sh"]
    ports: 
      - 1972
      - 9692:52773
      - 53773
      - "9592:9292"
    volumes:
      - ./:/irisrun/repo
